import { pgTable, uuid, text, integer, timestamp, numeric, boolean, jsonb } from 'drizzle-orm/pg-core';

export const listings = pgTable('listings', {
  id: uuid('id').primaryKey().defaultRandom(),
  externalId: text('external_id').unique(),
  source: text('source').notNull(),
  sourceUrl: text('source_url').notNull(),
  title: text('title').notNull(),
  description: text('description'),
  listingLanguage: text('listing_language').notNull().default('de'),
  address: text('address'),
  city: text('city'),
  postalCode: text('postal_code'),
  canton: text('canton'),
  latitude: numeric('latitude'),
  longitude: numeric('longitude'),
  rooms: numeric('rooms'),
  area: integer('area_m2'),
  price: integer('price_chf'),
  priceType: text('price_type').default('month'),
  floor: integer('floor'),
  availableFrom: timestamp('available_from', { withTimezone: true }),
  images: jsonb('images').$type<string[]>().default([]),
  features: jsonb('features').$type<string[]>().default([]),
  isActive: boolean('is_active').notNull().default(true),
  scrapedAt: timestamp('scraped_at', { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
